---
title: "R Notebook"
output: html_notebook
---




```{r}
require (data.table)
require (lubridate)
require (ggplot2)
library(readr)        # Package to read data, .csv files
library(tidyverse)
library(magrittr)     # To include pipe like operator %>%
library(dplyr)
```


```{r}
GHG_marginal_emissions <- fread("2017_RT5M_Marginal_Emissions_Rates_Dataframe.csv")

# add meta data
GHG_marginal_emissions[ , year := year(Date_Time_Pacific)]
GHG_marginal_emissions[ , month := month(Date_Time_Pacific)]
GHG_marginal_emissions[ , wday := wday(Date_Time_Pacific, label = TRUE)]
GHG_marginal_emissions[ , dhour := hour(Date_Time_Pacific)]
GHG_marginal_emissions[ , daytype := "weekday"]
GHG_marginal_emissions[ wday == "Sat" | wday == "Sun", daytype := "weekend"]
GHG_marginal_emissions[ , dayOfyear := yday(Date_Time_Pacific)]

# Make a summary table for North path and South path
GHG_me_NP <- GHG_marginal_emissions[ , .(avg_rate = mean(`RT5M_NP15_Emissions_Rate`)), by = .(month, dhour, daytype)]
GHG_me_SP <- GHG_marginal_emissions[ , .(avg_rate = mean(`RT5M_SP15_Emissions_Rate`)), by = .(month, dhour, daytype)]

# Plot North Path 15 GHG marginal emission rate
ggplot(GHG_me_NP, aes(x = dhour, y = avg_rate)) + geom_line(aes(linetype = daytype)) + theme_gray(base_size = 13) + facet_wrap("month") + labs(x = "Hour of Day", y = "Emissions(kg/kWh)")
# Plot South Path 15 GHG marginal emission rate
ggplot(GHG_me_SP, aes(x = dhour, y = avg_rate)) + geom_line(aes(linetype = daytype)) + theme_gray(base_size = 13) + facet_wrap("month") + labs(x = "Hour of Day", y = "Emissions(kg/kWh)")

```

```{r}
GHG_NP_hour <- GHG_marginal_emissions %>% 
  mutate(Hr = dhour + 1) %>% 
   group_by(month, dayOfyear, Hr) %>%
   summarise(GHG_hourly = mean(RT5M_NP15_Emissions_Rate)) 
```

